---
- hosts: all
  tasks:
  - name: install apache
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"] 
  - name: update packages
    apt:
      update_cache: yes
    when: ansible_ditribution in ["Debian", "Ubuntu"]
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
