---
- hosts: all
  tasks:
  - name: install apache
    apt:
      name: apache2
      state: latest 
  - name: update packages
    apt:
      update_cache: yes
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
